{
 "title": "PEPPER / MOTAN / OUTGOING",
 "tags": [
  "motan",
  "outgoing"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "jobname", "label": "jobname", "query": "${VAR_JOBNAME}" },
   {
    "name": "app",
    "label": "app",
    "query": "label_values(up{job=\"$jobname\"}, appId)"
   }
  ]
 },
 "panels": [
  {
   "title": "QPS By Method",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by(method) (rate(app_motan_request_out_summary_seconds_count{app=~\"$app\"}[3m]))",
     "legendFormat": "{{method}}"
    }
   ]
  },
  {
   "title": "MAX P99 By Method",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 0 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "max(app_motan_request_out_summary_seconds{appId=\"$app\",quantile=\"0.99\"}) by (method)",
     "legendFormat": "{{method}}"
    }
   ]
  },
  {
   "title": "并发 By Method",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum (app_motan_request_out_concurrent_gauge{appId=~\"$app\"} offset 1m ) by (method)",
     "legendFormat": "{{method}}"
    }
   ]
  },
  {
   "title": "ERR By Method - 2m",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 0 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum(increase(app_motan_request_out_err_counter_total{appId=~\"$app\"}[2m])) by (method)",
     "legendFormat": "{{method}}"
    }
   ]
  },
  {
   "title": "QPS By Instance",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by(pod) (rate(app_motan_request_out_summary_seconds_count{appId=~\"$app\"}[3m]))",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "MAX P99 By Instance",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 5 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "max(app_motan_request_out_summary_seconds{appId=\"$app\",quantile=\"0.99\"}) by (pod)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "并发 By Instance",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 5 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum (app_motan_request_out_concurrent_gauge{appId=~\"$app\"} offset 1m ) by (pod)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "ERR By Instance - 2m",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 5 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum(increase(app_motan_request_out_err_counter_total{appId=~\"$app\"}[2m])) by (pod)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "请点击服务名进入详情",
   "type": "table",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "sum by(method) (rate(app_motan_request_out_summary_seconds_count{app=\"$app\"}[3m]))",
     "legendFormat": "QPS"
    },
    {
     "expr": "((\n  sum by(method) (increase(app_motan_request_out_err_counter{app=\"$app\"}[10m]))\n  / \n  (sum by(method) (increase(app_motan_request_out_summary_seconds_count{}[10m])) + 0.0001)\n  ) * 100)",
     "legendFormat": "错误率"
    },
    {
     "expr": "sum by (method) (max_over_time(app_motan_request_out_summary_seconds{app=\"$app\", quantile=\"0.99\"}[10m]) )",
     "legendFormat": "P99"
    },
    {
     "expr": "sum by (method) (max_over_time(app_motan_request_out_summary_seconds{app=\"$app\", quantile=\"0.999\"}[10m]) )",
     "legendFormat": "P999"
    },
    {
     "expr": "sum (app_motan_request_out_concurrent_gauge{app=\"$app\"} offset 1m ) by (method)",
     "legendFormat": "并发"
    }
   ]
  }
 ]
}