{
 "title": "PEPPER / Dashboard",
 "tags": [
  "dashboard",
  "incoming",
  "pepper"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "jobname", "label": "jobname", "query": "${VAR_JOBNAME}" },
   {
    "name": "app",
    "label": "app",
    "query": "label_values(up{job=\"$jobname\"}, appId)"
   }
  ]
 },
 "panels": [
  {
   "title": "HTTP Incoming QPS",
   "type": "graph",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by(app) (rate(http_summary_seconds_count{appId=~\"$app\"}[3m])) >0",
     "legendFormat": "{{app}}"
    },
    {
     "expr": "sum by(app) (rate(pepper_summary_http_in_duration_seconds_count{appId=~\"$app\"}[3m])) >0",
     "legendFormat": "{{app}}"
    }
   ]
  },
  {
   "title": "HTTP 并发",
   "type": "graph",
   "gridPos": { "h": 4, "w": 8, "x": 8, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum (http_concurrent_gauge{app=~\"$app\"} offset 1m ) by (app)",
     "legendFormat": "{{app}}"
    },
    {
     "expr": "sum (pepper_gauge_http_in_concurrent{app=~\"$app\"} offset 1m ) by (app)",
     "legendFormat": "{{app}}"
    }
   ]
  },
  {
   "title": "HTTP Incoming P99",
   "type": "graph",
   "gridPos": { "h": 4, "w": 8, "x": 16, "y": 0 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "max(http_summary_seconds{app=~\"$app\",quantile=\"0.99\"}) by (app)",
     "legendFormat": "{{app}}"
    },
    {
     "expr": "max(pepper_summary_http_in_duration_seconds{app=~\"$app\",quantile=\"0.99\"}) by (app)",
     "legendFormat": "{{app}}"
    }
   ]
  },
  {
   "title": "Motan Incoming QPS",
   "type": "graph",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 4 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by(app) (rate(app_motan_request_in_summary_seconds_count{app=~\"$app\"}[3m]))",
     "legendFormat": "{{app}}"
    },
    {
     "expr": "sum by(app) (rate(pepper_summary_motan_in_duration_seconds_count{app=~\"$app\"}[3m]))",
     "legendFormat": "{{app}}"
    }
   ]
  },
  {
   "title": "Motan 并发",
   "type": "graph",
   "gridPos": { "h": 4, "w": 8, "x": 8, "y": 4 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum (app_motan_request_in_concurrent_gauge{app=~\"$app\"} offset 1m ) by (app)",
     "legendFormat": "{{app}}"
    },
    {
     "expr": "sum (pepper_gauge_motan_in_concurrent{app=~\"$app\"} offset 1m ) by (app)",
     "legendFormat": "{{app}}"
    }
   ]
  },
  {
   "title": "Motan Incoming P99",
   "type": "graph",
   "gridPos": { "h": 4, "w": 8, "x": 16, "y": 4 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "max(app_motan_request_in_summary_seconds{app=~\"$app\",quantile=\"0.99\"}) by (app)",
     "legendFormat": "{{app}}"
    },
    {
     "expr": "max(pepper_summary_motan_in_duration_seconds{app=~\"$app\",quantile=\"0.99\"}) by (app)",
     "legendFormat": "{{app}}"
    }
   ]
  },
  {
   "title": "HTTP 4XX/5XX Error - 累计值",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum by (app)(http_status_summary_seconds_count{status=~\"4..\"})",
     "legendFormat": "{{app}} - 4XX"
    },
    {
     "expr": "sum by (app)(http_status_summary_seconds_count{status=~\"5..\"})",
     "legendFormat": "{{app}} - 5XX"
    },
    {
     "expr": "sum by (app)(pepper_summary_http_status_in_duration_seconds_count{status=~\"4..\"})",
     "legendFormat": "{{app}} - 4XX"
    },
    {
     "expr": "sum by (app)(pepper_summary_http_status_in_duration_seconds_count{status=~\"5..\"})",
     "legendFormat": "{{app}} - 5XX"
    }
   ]
  },
  {
   "title": "HTTP Exception - 累计值",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 8 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum by (app)(http_err_counter{app=~\"$app\"})",
     "legendFormat": "{{app}} "
    },
    {
     "expr": "sum by (app)(pepper_counter_http_in_err_total{app=~\"$app\"})",
     "legendFormat": "{{app}} "
    }
   ]
  },
  {
   "title": "Motan Incoming Error - 2min",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum by(app) (increase(app_motan_request_in_err_counter_total{appId=~\"$app\"}[2m]))",
     "legendFormat": "{{app}}"
    },
    {
     "expr": "sum by(app) (increase(pepper_counter_motan_in_err_total{appId=~\"$app\"}[2m]))",
     "legendFormat": "{{app}}"
    }
   ]
  },
  {
   "title": "Motan Outgoing Error - 2min",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 8 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum by(app) (increase(app_motan_request_out_err_counter_total{appId=~\"$app\"}[2m]))",
     "legendFormat": "{{app}}"
    },
    {
     "expr": "sum by(app) (increase(pepper_counter_motan_out_err_total{appId=~\"$app\"}[2m]))",
     "legendFormat": "{{app}}"
    }
   ]
  },
  {
   "title": "HTTP Incoming",
   "type": "table",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 13 },
   "targets": [
    {
     "expr": " sum\n  by(app) (rate(pepper_summary_http_in_duration_seconds_count{app=~\"$app\"}[3m] offset\n  1m))"
    },
    {
     "expr": "sum\n  by(app) (pepper_gauge_http_in_concurrent{appId=~\"$app\"} offset 1m)"
    },
    {
     "expr": "max(pepper_summary_http_in_duration_seconds{app=~\"$app\",quantile=\"0.99\"}) by (app)"
    },
    {
     "expr": "max(pepper_summary_http_in_duration_seconds{app=~\"$app\",quantile=\"0.999\"}) by (app)"
    }
   ]
  },
  {
   "title": "Motan Incoming",
   "type": "table",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 13 },
   "targets": [
    {
     "expr": "sum\n  by(app) (rate(pepper_summary_motan_in_duration_seconds_count{app=~\"$app\"}[3m] offset\n  1m))"
    },
    {
     "expr": "sum\n  by(app) (pepper_gauge_motan_in_concurrent{app=~\"$app\"} offset 1m)"
    },
    {
     "expr": "max(pepper_summary_motan_in_duration_seconds{app=~\"$app\",quantile=\"0.99\"}) by (app)"
    },
    {
     "expr": "max(pepper_summary_motan_in_duration_seconds{app=~\"$app\",quantile=\"0.999\"}) by (app)"
    }
   ]
  }
 ]
}