{
 "title": "PEPPER / MOTAN / INCOMING / DRILL",
 "tags": [
  "incoming",
  "motan"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "app",
    "label": "app",
    "query": "label_values(up{job=\"pepper_exporter_k8s\"}, appId)"
   },
   {
    "name": "method",
    "label": "method",
    "query": "query_result(sum(increase(app_motan_requests_in_latency_seconds_histogram_count{appId=\"$app\"}[1d])) by (method) > 30) "
   }
  ]
 },
 "panels": [
  { "title": "Motan：Incoming - $method", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }, "repeat": "method" },
  {
   "title": "QPS",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by(pod) (rate(app_motan_request_in_summary_seconds_count{app=~\"$app\", method=~\"$method\"}[3m]))",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "P90",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 1 },
   "repeat": "motan",
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "max(app_motan_request_in_summary_seconds{appId=\"$app\", quantile=\"0.9\", method=~\"$method\"}) by (pod)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "P99",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "max(app_motan_request_in_summary_seconds{appId=\"$app\", quantile=\"0.99\", method=~\"$method\"}) by (pod)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "P999",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 1 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "max(app_motan_request_in_summary_seconds{appId=\"$app\", quantile=\"0.999\", method=~\"$method\"}) by (pod)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "并发",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "floor(sum (app_motan_request_in_concurrent_gauge{appId=~\"$app\", method=~\"$method\"} offset 1m ) by (pod))",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "P90对比",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 9 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "max(app_motan_request_in_summary_seconds{appId=\"$app\", quantile=\"0.9\", method=~\"$method\"})",
     "legendFormat": "P99"
    },
    {
     "expr": "max(app_motan_request_in_summary_seconds{appId=\"$app\", quantile=\"0.9\", method=~\"$method\"} offset 24h)",
     "legendFormat": "P99 - Last Day"
    },
    {
     "expr": "max(app_motan_request_in_summary_seconds{appId=\"$app\", quantile=\"0.9\", method=~\"$method\"} offset 7d)",
     "legendFormat": "P99 - Last Week"
    }
   ]
  },
  {
   "title": "P99对比",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "max(app_motan_request_in_summary_seconds{appId=\"$app\", quantile=\"0.99\", method=~\"$method\"}) by (pod)",
     "legendFormat": "P99"
    },
    {
     "expr": "max(app_motan_request_in_summary_seconds{appId=\"$app\", quantile=\"0.99\", method=~\"$method\"} offset 24h) by (pod)",
     "legendFormat": "P99 - Last Day"
    },
    {
     "expr": "max(app_motan_request_in_summary_seconds{appId=\"$app\", quantile=\"0.99\", method=~\"$method\"} offset 7d) by (pod)",
     "legendFormat": "P99 - Last Week"
    }
   ]
  },
  {
   "title": "P999对比",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 9 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "max(app_motan_request_in_summary_seconds{appId=\"$app\", quantile=\"0.999\", method=~\"$method\"}) by (pod)",
     "legendFormat": "P99"
    },
    {
     "expr": "max(app_motan_request_in_summary_seconds{appId=\"$app\", quantile=\"0.999\", method=~\"$method\"} offset 24h) by (pod)",
     "legendFormat": "P99 - Last Day"
    },
    {
     "expr": "max(app_motan_request_in_summary_seconds{appId=\"$app\", quantile=\"0.999\", method=~\"$method\"} offset 7d) by (pod)",
     "legendFormat": "P99 - Last Week"
    }
   ]
  },
  {
   "title": "错误数 - 1m",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum(increase(app_motan_request_in_err_counter{appId=~\"$app\"}[1m]))",
     "legendFormat": "错误数 - 1m"
    }
   ]
  }
 ]
}